package Celcius;
// Generated 11 jun 2024, 15:01:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private int idAlbum;
	private Artista artista;
	private String codigoBarras;
	private String titulo;
	private byte numeroCopias;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Album() {
	}

	public Album(int idAlbum, Artista artista, String codigoBarras, String titulo, byte numeroCopias) {
		this.idAlbum = idAlbum;
		this.artista = artista;
		this.codigoBarras = codigoBarras;
		this.titulo = titulo;
		this.numeroCopias = numeroCopias;
	}

	public Album(int idAlbum, Artista artista, String codigoBarras, String titulo, byte numeroCopias,
			Set<Venta> ventas) {
		this.idAlbum = idAlbum;
		this.artista = artista;
		this.codigoBarras = codigoBarras;
		this.titulo = titulo;
		this.numeroCopias = numeroCopias;
		this.ventas = ventas;
	}

	public int getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(int idAlbum) {
		this.idAlbum = idAlbum;
	}

	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	public String getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(String codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public byte getNumeroCopias() {
		return this.numeroCopias;
	}

	public void setNumeroCopias(byte numeroCopias) {
		this.numeroCopias = numeroCopias;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
