package Celcius;
// Generated 11 jun 2024, 15:01:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista implements java.io.Serializable {

	private int idArtista;
	private String nombreArtista;
	private Set<Album> albums = new HashSet<Album>(0);

	public Artista() {
	}

	public Artista(int idArtista, String nombreArtista) {
		this.idArtista = idArtista;
		this.nombreArtista = nombreArtista;
	}

	public Artista(int idArtista, String nombreArtista, Set<Album> albums) {
		this.idArtista = idArtista;
		this.nombreArtista = nombreArtista;
		this.albums = albums;
	}

	public int getIdArtista() {
		return this.idArtista;
	}

	public void setIdArtista(int idArtista) {
		this.idArtista = idArtista;
	}

	public String getNombreArtista() {
		return this.nombreArtista;
	}

	public void setNombreArtista(String nombreArtista) {
		this.nombreArtista = nombreArtista;
	}

	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

}
