package Celcius;
// Generated 11 jun 2024, 15:01:16 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private int idCliente;
	private String nombreCompleto;
	private String direccion;
	private String correo;
	private String telefono;
	private String foto;
	private Set<Venta> ventas = new HashSet<Venta>(0);

	public Cliente() {
	}

	public Cliente(int idCliente, String nombreCompleto, String direccion, String telefono, String foto) {
		this.idCliente = idCliente;
		this.nombreCompleto = nombreCompleto;
		this.direccion = direccion;
		this.telefono = telefono;
		this.foto = foto;
	}

	public Cliente(int idCliente, String nombreCompleto, String direccion, String correo, String telefono, String foto,
			Set<Venta> ventas) {
		this.idCliente = idCliente;
		this.nombreCompleto = nombreCompleto;
		this.direccion = direccion;
		this.correo = correo;
		this.telefono = telefono;
		this.foto = foto;
		this.ventas = ventas;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public Set<Venta> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<Venta> ventas) {
		this.ventas = ventas;
	}

}
