package Celcius;
// Generated 11 jun 2024, 15:01:16 by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private Integer idVenta;
	private Album album;
	private Cliente cliente;
	private Date fecha;

	public Venta() {
	}

	public Venta(Album album, Cliente cliente) {
		this.album = album;
		this.cliente = cliente;
	}

	public Venta(Album album, Cliente cliente, Date fecha) {
		this.album = album;
		this.cliente = cliente;
		this.fecha = fecha;
	}

	public Integer getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(Integer idVenta) {
		this.idVenta = idVenta;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
